import {
  FileText,
  Sparkles,
  TrendingUp,
  Clock,
  MoreHorizontal,
} from "lucide-react";

const posts = [
  {
    title: "Why AI Agents Are Changing Software Development",
    platform: "LinkedIn",
    status: "Published",
    reach: "12.4K",
    engagement: "8.7%",
    time: "2 hours ago",
  },
  {
    title: "The Future of Autonomous AI",
    platform: "X",
    status: "Published",
    reach: "8.9K",
    engagement: "6.4%",
    time: "5 hours ago",
  },
  {
    title: "5 Things Developers Should Know About AI Agents",
    platform: "LinkedIn",
    status: "Scheduled",
    reach: "—",
    engagement: "—",
    time: "Tomorrow, 10:00",
  },
];

export default function Posts() {
  return (
    <div className="space-y-8">

      {/* Header */}
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end">

        <div>
          <p className="mb-2 text-sm font-medium text-blue-400">
            CONTENT ENGINE
          </p>

          <h1 className="text-3xl font-bold text-white md:text-4xl">
            Posts
          </h1>

          <p className="mt-2 text-slate-400">
            Content created and managed autonomously by your AI.
          </p>
        </div>

        <button className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white transition hover:bg-blue-500">
          <Sparkles className="h-4 w-4" />
          Generate Post
        </button>

      </div>

      {/* Stats */}
      <div className="grid gap-5 md:grid-cols-3">

        <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5">
          <div className="flex items-center gap-3">
            <FileText className="h-5 w-5 text-blue-400" />
            <span className="text-sm text-slate-400">
              Total Posts
            </span>
          </div>

          <p className="mt-3 text-3xl font-bold text-white">
            24
          </p>

          <p className="mt-1 text-sm text-green-400">
            +18.4% this month
          </p>
        </div>

        <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5">
          <div className="flex items-center gap-3">
            <TrendingUp className="h-5 w-5 text-green-400" />
            <span className="text-sm text-slate-400">
              Average Engagement
            </span>
          </div>

          <p className="mt-3 text-3xl font-bold text-white">
            8.6%
          </p>

          <p className="mt-1 text-sm text-green-400">
            +12.3% improvement
          </p>
        </div>

        <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5">
          <div className="flex items-center gap-3">
            <Clock className="h-5 w-5 text-purple-400" />
            <span className="text-sm text-slate-400">
              Scheduled
            </span>
          </div>

          <p className="mt-3 text-3xl font-bold text-white">
            7
          </p>

          <p className="mt-1 text-sm text-slate-400">
            Next post tomorrow
          </p>
        </div>

      </div>

      {/* Posts list */}
      <div className="rounded-2xl border border-slate-800 bg-slate-900/70">

        <div className="border-b border-slate-800 px-6 py-5">
          <h2 className="font-semibold text-white">
            Recent Content
          </h2>

          <p className="mt-1 text-sm text-slate-400">
            Posts generated by the autonomous creator.
          </p>
        </div>

        <div className="divide-y divide-slate-800">

          {posts.map((post) => (
            <div
              key={post.title}
              className="flex flex-col gap-5 px-6 py-5 transition hover:bg-slate-800/30 lg:flex-row lg:items-center lg:justify-between"
            >

              {/* Post information */}
              <div className="flex min-w-0 items-start gap-4">

                <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-blue-500/10">
                  <FileText className="h-5 w-5 text-blue-400" />
                </div>

                <div className="min-w-0">

                  <h3 className="font-semibold text-white">
                    {post.title}
                  </h3>

                  <div className="mt-2 flex flex-wrap items-center gap-2 text-sm">

                    <span className="text-slate-400">
                      {post.platform}
                    </span>

                    <span className="text-slate-600">
                      •
                    </span>

                    <span
                      className={
                        post.status === "Published"
                          ? "text-green-400"
                          : "text-yellow-400"
                      }
                    >
                      {post.status}
                    </span>

                    <span className="text-slate-600">
                      •
                    </span>

                    <span className="text-slate-500">
                      {post.time}
                    </span>

                  </div>

                </div>

              </div>

              {/* Metrics */}
              <div className="flex items-center gap-8">

                <div>
                  <p className="text-xs text-slate-500">
                    REACH
                  </p>

                  <p className="mt-1 font-semibold text-white">
                    {post.reach}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-slate-500">
                    ENGAGEMENT
                  </p>

                  <p className="mt-1 font-semibold text-white">
                    {post.engagement}
                  </p>
                </div>

                <button className="rounded-lg p-2 text-slate-400 transition hover:bg-slate-800 hover:text-white">
                  <MoreHorizontal className="h-5 w-5" />
                </button>

              </div>

            </div>
          ))}

        </div>

      </div>

      {/* Autonomous generation */}
      <div className="rounded-2xl border border-blue-500/20 bg-blue-500/5 p-6">

        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">

          <div className="flex items-start gap-4">

            <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-blue-500/10">
              <Sparkles className="h-6 w-6 text-blue-400" />
            </div>

            <div>
              <h3 className="font-semibold text-white">
                Autonomous Content Generation
              </h3>

              <p className="mt-1 text-sm text-slate-400">
                AI continuously discovers topics and creates new content
                based on your persona.
              </p>
            </div>

          </div>

          <div className="flex items-center gap-2 text-sm font-medium text-green-400">
            <span className="h-2.5 w-2.5 rounded-full bg-green-400" />
            Running
          </div>

        </div>

      </div>

    </div>
  );
}